server:
  port: 8081

spring:
  application:
    name: url-shortener-sb

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}
    hibernate:
      ddl-auto: update

jwt:
  expiration: ${JWT_EXPIRATION}
  secret: ${JWT_SECRET}
